apiVersion: autoscaling/v3
kind: HorizontalPodAutoscaler
metadata:
  name: eureka-server-hpa
  namespace: nyamnyam
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: eureka-server
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70