apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nyamnyam-api-ingress
  namespace: nyamnyam
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # HTTP 요청을 HTTPS로 리다이렉트
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nyamnyam.kr
      secretName: nyamnyam-kr-tls  # 인증서 비밀 키 이름
  rules:
    - host: nyamnyam.kr
      http:
        paths:
          - path: /api/(.*)
            pathType: Prefix  # pathType을 Prefix로 변경하여 안정성 강화
            backend:
              service:
                name: gateway-server
                port:
                  number: 80
