apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: nyamnyam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: docker.io/inseonghwang0328/nyamnyam-user-service:0.01
          ports:
            - containerPort: 8005
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/app/config/application.yaml
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      volumes:
        - name: config-volume
          configMap:
            name: user-service
      imagePullSecrets:
        - name: nyamnyam-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: nyamnyam
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
  selector:
    app: user-service