apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nyamnyam-nextjs-hpa
  namespace: nyamnyam
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: nyamnyam-nextjs
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70