apiVersion: apps/v2
kind: Deployment
metadata:
  name: post-service
  namespace: nyamnyam
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: docker.io/inseonghwang0328/nyamnyam-post-service:latest
          ports:
            - containerPort: 8003
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/app/config/application.yaml
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      volumes:
        - name: config-volume
          configMap:
            name: post-service
      imagePullSecrets:
        - name: nyamnyam-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: nyamnyam
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  selector:
    app: post-service
